# Anreicherung usedFor aus subject für die Suche (daher reduziert mit uniques)
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: subject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['usedFor_display_mv'].value,
          x,
          x,
          null
        )
      ).uniques().join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: subject_usedFor_mv
  columnInsertIndex: 2
