# title (Jahresangabe aus dateLifespanStart-Jahresangabe aus dateLifespanEnd)
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      cells['title'].value,
      x,
      x,
      'ohne Titel'
    )
    + forNonBlank(
      forNonBlank(
        cells['dateLifespanStart'].value,
        x,
        x[0,4],
        ''
      )
      + forNonBlank(
        cells['dateLifespanEnd'].value,
        x,
        'â€“' + x[0,4],
        ''
      ),
      x,
      ' (' + x + ')',
      ''
    )
  newColumnName: display
  columnInsertIndex: 1
