# Trefferliste dritte Zeile
# GND-Relation nur Indikator berc_Ts und beru_TS
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          cells['gndRelation_text_mv'].value,
          v,
          forEachIndex(
            v.split('␟'),
            i,
            x,
            if(
              or(
                cells['gndRelation_type_mv'].value.split('␟')[i].contains('Beruf/Funktion'),
                cells['gndRelation_type_mv'].value.split('␟')[i].contains('Charakt. Beruf')
              ),
              if(
                not(x == '␣'),
                x,
                null
              ),
              null
            )
          ).join('␟'),
          null
        ),
        forNonBlank(
          filter(
            cells['occupation_mv'].value.split('␟'),
            v,
            not(v == '␣')
          ).join('␟'),
          x,
          x,
          null
        )
      ].join('␟'),
      z,
      z.split('␟').uniques().join(', '),
      null
    )
  newColumnName: displayAddition1
  columnInsertIndex: 1
