# Für alle Felder mit Kallías-ID die dazugehörige Bezeichnung in _display anreichern
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: classificationAuthor_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('sy','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: classificationAuthor_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: classificationForm_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('sy','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: classificationForm_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: classificationSubject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('sy','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: classificationSubject_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: corporation_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ks','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: corporation_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: person_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('pe','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: person_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: subject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: subject_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: work_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ak','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: work_display_mv
  columnInsertIndex: 2
