# Für alle Felder mit Kallías-ID die dazugehörige Bezeichnung in _display anreichern
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: accession_id
  expression: |
    grel:
    forNonBlank(
      value.cross('be','id')[0].cells['display'].value,
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: accession_display
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: corporationAbout_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ks','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: corporationAbout_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: corporationAt_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ks','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: corporationAt_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: corporationBy_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ks','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: corporationBy_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: corporationTo_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ks','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: corporationTo_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: digitalObject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('mm','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: digitalObject_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: collection_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('bf','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: collection_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: item_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('au','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: item_manifestation_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ak','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_manifestation_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: library_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ak','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: library_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: manuscript_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('hs','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: manuscript_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: parent_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('bi','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: parent_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: personAbout_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('pe','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: personAbout_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: personAt_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('pe','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: personAt_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: personBy_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('pe','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: personBy_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: personTo_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('pe','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: personTo_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: work_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ak','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: work_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: subject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: subject_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: subjectLocation_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: subjectLocation_display_mv
  columnInsertIndex: 2
