# Für alle Felder mit Kallías-ID die dazugehörige Bezeichnung in _display anreichern
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: child_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: child_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: parent_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: parent_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: seeAlso_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: seeAlso_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: usedFor_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: usedFor_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: useTerm_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('th','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: useTerm_display_mv
  columnInsertIndex: 2
