# Für alle Felder mit Kallías-ID die dazugehörige Bezeichnung in _display anreichern
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: corporationAt_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ks','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: corporationAt_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: personAt_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('pe','id')[0].cells['display'].value,
          x,
          x,
          v
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: personAt_display_mv
  columnInsertIndex: 2
