# Verknüpfte digitale Objekte ermittelt über zugehörige Exemplare
# synchron zu item_id_mv, mehrere verknüpfte Informationen getrennt mit ␝ (U+241D)
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_accessLevel_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_accessLevel_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_display_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_display_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_id_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_id_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_fileExtension_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_fileExtension_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_hyperlink_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_hyperlink_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_license_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_license_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_licenseNote_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_licenseNote_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['digitalObject_thumbnail_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␝|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: item_digitalObject_thumbnail_mv
  columnInsertIndex: 2
