# Facette Ort
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          forEachIndex(
            cells['relation_type_mv'].value.split('␟'),
            i,
            v,
            if(
              or(
                v == 'Sterbeort: Geografikum',
                v == 'Geburtsort: Geografikum',
                v == 'Wirkungsort: Geografikum',
                v == 'Geografikum, allgemein'
              ),
              forNonBlank(
                forEach(
                  cells['relation_text_mv'].value.split('␟')[i].split(';'),
                  x,
                  forNonBlank(
                    x.replace('␣','').replace('ohne Ort','').replace('[u.a.]','').replace('und andere','').trim(),
                    xx,
                    xx,
                    null
                  )
                ).join('␟'),
                z,
                z,
                null
              ),
              null
            )
          ).join('␟'),
          x,
          x,
          null
        )
      ].uniques().join('␟'),
      x,
      forEach(
        x.split('␟'),
        v,
        with(
          if(
            v.startsWith('('),
            v.replace('(','').replace(')',''),
            if(
              v.startsWith('['),
              v.replace('[','').replace(']',''),
              v
            )
          ),
          vv,
          with(
            if(
              vv.startsWith('␝'),
              null,
              vv
            ),
            vvv,
            if(
              vvv.find('[').length() != vvv.find(']').length(),
              vvv.replace('[','').replace(']',''),
              vvv
            )
          )
        )
      ).join('␟'),
      null
    )
  newColumnName: filterLocation_mv
  columnInsertIndex: 2
