# Filter Digital (Boolean)
# true wenn ein digitales Objekt vorhanden ist, das nicht "/dbst02/" in der URL beinhaltet
# true wenn categorySub = "Elektronisches Dokument"
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    if(
      or(
        forNonBlank(
          cells['digitalObject_hyperlink_mv'].value,
          v,
          filter(
            cells['digitalObject_hyperlink_mv'].value.split('␟'),
            v,
            and(
              not(v.contains('/dbst02/')),
              v != '␣'
            )
          ).length(),
          0
        ) > 0,
        forNonBlank(
          cells['categorySub'].value,
          v,
          v == 'Elektronisches Dokument',
          false
        )
      ),
      true,
      null
    )
  newColumnName: filterDigital
  columnInsertIndex: 2