# Filter Mehrteilig (Boolean)
# nur Konvolute
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    if(
      cells['category'].value == 'Konvolut',
      true,
      null
    )
  newColumnName: filterMultipart
  columnInsertIndex: 2