# Suche nach Normdaten-Identifiern
- op: core/column-addition
  engineConfig:
    facets:
    - type: text
      columnName: categoryIndex_mv
      query: "KÃ¶rperschaft|Konferenz|Verlag"
      mode: regex
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    value
  newColumnName: searchEntity_id_mv
  columnInsertIndex: 2
