# Suchbegriffe für die Autovervollständigung
- op: core/column-addition
  engineConfig:
    facets:
    - type: text
      columnName: categoryIndex_mv
      query: "Körperschaft|Konferenz|Verlag"
      mode: regex
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    cells['display'].value
    + forNonBlank(
      cells['nameAlternative_name_mv'].value,
      v,
      '␟' + v,
      '' 
    )
    + forNonBlank(
      cells['nameOriginal_mv'].value,
      v,
      '␟' + v,
      '' 
    )
  newColumnName: searchSuggestTerm_mv
  columnInsertIndex: 2
